---
- name: Add apt_key ID
  apt_key:
    url: https://apt.dockerproject.org/gpg
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add an entry for your Ubuntu operationg system
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present
    filename: docker.list
    update_cache: yes

- name: Install the recommended kernel package, linux-image-extra-*
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual

- name: Install docker-engine
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-engine
    - golang
    - python-dev
    - python-pip

- name: Install docker-compose
  pip:
    name: "{{ item }}"
  with_items:
    - docker-compose
    - docker-py

- name: "add {{ app_user }} to docker group"
  user:
    name: "{{ app_user }}"
    groups: adm,docker
    shell: /bin/bash
    state: present

- name: Set docker.service.d
  file:
    path: /lib/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: xenial

- name: Set docker.service for systemd
  template:
    src: docker.j2
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0644
  notify: restart-service-docker
  tags: xenial

- name: set docker.service
  copy:
    src: docker.service
    dest: /lib/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
  notify: restart-systemd-docker
  tags: xenial

- name: set docker.service
  copy:
    src: docker-opts.conf
    dest: /lib/systemd/system/docker.service.d/docker-opts.conf
    owner: root
    group: root
    mode: 0644
  notify: restart-systemd-docker
  tags: xenial

- name: Set http-proxy.conf for docker registory.(xenial)
  template:
    src: http-proxy.conf.j2
    dest: /lib/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0644
  notify: restart-systemd-docker
  tags: xenial

- meta: flush_handlers

