---
- name: restart-systemd-docker
  shell: systemctl restart docker

- name: restart-service-docker
  service:
    name: docker
    state: restarted
    enabled: yes

- name: systemd-daemon-reload
  shell: systemctl daemon-reload

