---
- name: restart-systemd-docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: restart-service-docker
  service:
    name: docker
    state: restarted
    enabled: yes
